
[env]
TERM = "xterm-256color"

[window]

opacity = 0.8
blur = true

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

option_as_alt = "Both"

[font]

normal.family = "MesloLGS Nerd Font Mono"
bold.family = "MesloLGS Nerd Font Mono"
italic.family = "MesloLGS Nerd Font Mono"
bold_italic.family = "MesloLGS Nerd Font Mono"

size = 13.0

[general]
import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]
